apiVersion: v1
kind: Pod
metadata:
  name: sirius-pod
spec:
  containers:
  - name: sirius-prod
    image: us.gcr.io/valis-194104/sirius:prod
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: "/cache"
      name: "local-ssd"
  volumes:
  - name: "local-ssd"
    hostPath:
      path: "/mnt/disks/ssd0"
  nodeSelector:
    cloud.google.com/gke-local-ssd: "true"
    sirius: prod
