apiVersion: v1
kind: Pod
metadata:
  name: sirius-write-pod
spec:
  containers:
  - name: sirius-dev
    image: us.gcr.io/valis-194104/sirius:dev
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: "/cache"
      name: "local-ssd"
    - mountPath: "/pd"
      name: "sirius-cache"
  volumes:
  - name: "local-ssd"
    hostPath:
      path: "/mnt/disks/ssd0"
  - name: "sirius-cache"
    gcePersistentDisk:
      pdName: sirius-cache
      fsType: ext4
      readOnly: false
  nodeSelector:
    cloud.google.com/gke-local-ssd: "true"
