# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: yudongdev/gcloud-sdk:sirius

    working_directory: ~/SIRIUS-backend

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            docker build -t us.gcr.io/valis-194104/sirius:$CIRCLE_SHA1 .
            docker tag us.gcr.io/valis-194104/sirius:$CIRCLE_SHA1 us.gcr.io/valis-194104/sirius:dev
            docker tag us.gcr.io/valis-194104/sirius:dev app

      - run:
          name: Run tests inside Docker image
          command: |
            docker run -e GCLOUD_SERVICE_KEY=$GCLOUD_SERVICE_KEY us.gcr.io/valis-194104/sirius:$CIRCLE_SHA1 /app/docker_test.sh

      - run:
          name: prep-gcloud
          command: ./app/prep_gcloud.sh

      - run:
          name: Push Docker image and deploy on kubernetes
          command: ./.circleci/deploy.sh
