# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: yudongdev/gcloud-sdk:sirius

    working_directory: ~/SIRIUS-backend

    steps:
      - checkout

      - run:
          name: prep-gcloud
          command: ./.circleci/prep_gcloud.sh
  build-deploy:
    docker:
      - image: yudongdev/gcloud-sdk:sirius

    working_directory: ~/SIRIUS-backend

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          key: v1-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t us.gcr.io/valis-194104/sirius:$CIRCLE_SHA1 .
            docker tag us.gcr.io/valis-194104/sirius:$CIRCLE_SHA1 us.gcr.io/valis-194104/sirius:dev
            docker tag us.gcr.io/valis-194104/sirius:dev app

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - run:
          name: Push Docker image and deploy on kubernetes
          command: ./.circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test
      - build-deploy:
          requires:
            - build-test
          filters:
            branches:
              only: master